---
- name: Install lxml dependency for Ansible maven_artifact module.
  package:
    name: python-lxml
    state: present

- name: Download AEM quickstart artifact from Nexus.
  maven_artifact:
    group_id: "{{ item.group_id }}"
    artifact_id: "{{ item.artifact_id }}"
    repository_url: "{{ item.repository_url }}"
    dest: "{{ aem_download_path }}/{{ aem_quickstart_name }}"
    extension: jar
    username: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    version: "{{ item.version | default(aem_version_short) }}"
  with_items: "{{ aem_mvn_coordinates }}"