- name: Install AEM package.
  package:
    name: "{{ aem_package }}"
    state: present

- name: Copy AEM jar to download folder.
  copy:
    src: "{{ aem_package_home }}/{{ aem_quickstart_name }}"
    dest: "{{ aem_download_path }}"
    remote_src: True

- name: Remove AEM package.
  package:
    name: "{{ aem_package }}"
    state: absent