---
- name: Build AEM quickstart SHA1 checksum string.
  set_fact:
    _aem_quickstart_checksum: "sha1:{{ aem_quickstart_sha1 }}"
  when: aem_quickstart_sha1 is defined

- name: Download AEM quickstart from URL.
  get_url:
    url: "{{ aem_url }}"
    dest: "{{ aem_download_path }}/{{ aem_quickstart_name }}"
    url_username: "{{ aem_url_username | default(omit) }}"
    url_password: "{{ aem_url_password | default(omit) }}"
    checksum: "{{ _aem_quickstart_checksum | default(omit) }}"
