---
- name: Download AEM artifact from URL.
  get_url:
    url: "{{ aem_url }}"
    dest: "{{ aem_download_path }}/{{ aem_quickstart_name }}"
    url_username: "{{ aem_url_username | default(omit) }}"
    url_password: "{{ aem_url_password | default(omit) }}"
    checksum: "{{ aem_quickstart_checksum | default(omit) }}"
